yarnPath: .yarn/releases/yarn-sources.cjs
packageExtensions:
  debug@*:
    dependencies:
      supports-color: "*"
  node-fetch@*:
    dependencies:
      encoding: "*"
  fusion-plugin-i18n@*:
    dependencies:
      fusion-tokens: "*"
      fusion-plugin-universal-events: "*"
  fusion-build-sample@*:
    dependencies:
      fusion-tokens: "*"
      fusion-cli: "*"
  fusion-build@*:
    dependencies:
      fusion-tokens: "*"
      fusion-cli: "*"

